# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hands' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'RxSwift', '3.6.1'
  pod 'RxCocoa', '3.6.1'
  pod 'LineSDK', '~> 4.0.2'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'FirebaseUI/Database'

  target 'handsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'handsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
